/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.adtg;


public class App {

    public static void main(String[] args) {
        Grader grader = new Grader(args[0], args[1]);
        grader.mainFunction();
        // ScriptExecutor scriptExecutor = new ScriptExecutor();
        // scriptExecutor.execute();
    }
}
